# Generated by Django 3.2.6 on 2021-10-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='emailId',
        ),
    ]
