# Generated by Django 3.2.6 on 2021-10-03 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211003_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='mobileNo',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
