# Generated by Django 3.2.6 on 2021-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentinfo_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='mobileNo',
            field=models.IntegerField(),
        ),
    ]
